/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in created projects and kept here so TypeScript
// can resolve Next types before the first local dev run.
